helm install jumpserver . -n jms \
--set core.config.secretKey=GxrLH7rewfsRN8B9Zl6MEGD50Uou4LF6UV \
--set core.config.bootstrapToken=ilR8RvAbK7lgRTxs \
--set global.storageClass=jms-sc \
--set externalDatabase.engine=mysql \
--set externalDatabase.host=jms-mysql \
--set externalDatabase.port=3306 \
--set externalDatabase.user=jumpserver \
--set externalDatabase.password=jumpserver \
--set externalDatabase.database=jumpserver \
--set externalRedis.host=jms-redis-master \
--set externalRedis.port=6379 \
--set externalRedis.password=jumpserver \
--set koko.service.type=NodePort \
--set koko.service.nodePort=32222 \
--set web.service.type=NodePort \
--set web.service.nodePort=31111
